name: "Draft new release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The new version number you want to release.'
        required: true

jobs:
  draft-new-release:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create release branch
        run: git checkout -b release/${{ github.event.inputs.version }}

      - name: Build release files for Github Pages
        run: |
          npm ci
          npm run build:gh-pages

      # In order to make a commit, we need to initialize a user.
      - name: Initialize mandatory git config
        run: |
          git config user.name "No Name Release Bot"
          git config user.email noreply@github.com

      - name: Commit release files
        id: make-commit
        run: |
          git add -A
          git commit --message "Prepare release ${{ github.event.inputs.version }}"

      - name: Bump version in package.json
        run: npm version ${{ github.event.inputs.version }}

      - name: Push new branch
        run: git push origin release/${{ github.event.inputs.version }}

      - name: Create pull request
        uses: thomaseizinger/create-pull-request@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: release/${{ github.event.inputs.version }}
          base: master
          title: Release version ${{ github.event.inputs.version }}
          reviewers: ${{ github.actor }} # By default, we request a review from the person who triggered the workflow.
          # Write a nice message to the user.
          # We are claiming things here based on the `publish-new-release.yml` workflow.
          # You should obviously adopt it to say the truth depending on your release workflow :)
          body: |
            Hi @${{ github.actor }}!
            This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
            I've rebuilt the Github Pages files and bumped the versions in the manifest files to ${{ github.event.inputs.version }}.
            Merging this PR will update the live site.
